name: get-solution-version
# opens the solution.xml file located at solutions/PPContactManager/Other/Solution.xml
# ImportExportXml\SolutionManifest\Version

#<ImportExportXml >
#  <SolutionManifest>
#    <UniqueName>PPContactManager</UniqueName>
#    <LocalizedNames>
#      <LocalizedName description="PP Contact Manager" languagecode="1033" />
#    </LocalizedNames>
#    <Descriptions />
#    <Version>1.9.0.0</Version>

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Path to the solution file'
        required: true
        default: 'solutions/PPContactManager/Other/Solution.xml'

env:
  SOLUTION_FILE_PATH: 'solutions/PPContactManager/Other/Solution.xml'

jobs:
  get-solution-version:
    runs-on: ubuntu-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: get-solution-version-from-xml
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: ${{ env.SOLUTION_FILE_PATH }}
        xpath: '//Version'
        
    - name: write-out-version
      shell: bash
      run: echo ${{ steps.getxml.outputs.info }}
      
    - name: create-draft-release
      id: draft-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ steps.getxml.outputs.info }}"
        release_name: "${{ steps.getxml.outputs.info }}"
        draft: true
        prerelease: false

